title: DutchNews1
email: info@dutchnews1.nl
description: >-
  Een moderne nieuwssite uit Nederland met actuele berichtgeving, opinie en achtergrond.
baseurl: ""
url: "https://bnowee.github.io/dutchnews1"

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - vendor
